### PR TITLE
Update LICENSE_HEADER.md with Apache 2 License URL

### PR DESCRIPTION
**Pull request by frunkad**
Updated the URL at Line 74

## Description

Changed 

https://inside.corp.adobe.com/intellectual-property/copyrights.html#jcr-content_par_tab_Adobe-Copyright-Notices
to 
http://www.apache.org/licenses/LICENSE-2.0

## Related Issue

#10 

## Motivation and Context

The Copyright URL was of the Adobe Corporate instead of Apache Copyright URL

## How Has This Been Tested?

Markdown edit, doesn't require explicit testing.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by filmaj** [comment]
I think we could actually just remove this section as it is not that helpful.

**Comment by frunkad** [comment]
Shall I go ahead with removing the complete other license section or just the link line?

Also, though it might not be useful, having a direct link to the License file shares more detail and (personally) I believe it might be good to keep.

**Comment by filmaj** [comment]
Yes if you can remove the section that would be great, and I would accept the PR.

**Comment by frunkad** [comment]
Made the changes. Small confusion: I created a new commit to my fork's patch-1 branch. Does that also update this PR or do I need to do something extra?

**Comment by filmaj** [comment]
Lol, sorry, I meant just  remove the "for more info check out this corporate URL" section 🙈 

Maybe best to start fresh? I'll close this PR but if you're still up for it feel free to send another PR.

**Pull request closed without merging**
